'Close': [0, 0, 0, 0, 0] #Zero, close gripper and stop

'Up': [0, 1, 0, 0, 0] #One, Move robot arm up

'Down': [0, 1, 1, 0, 0] #Two, Move robot arm down

'Open': [1, 1, 1, 1, 1] #Five, Open gripper and stop

'Left': [1, 0, 0, 0, 0] #Six, Move left

'Right': [1, 1, 0, 0, 0] #Seven, Move right