arm_joint_names:
  - elbow_joint
  - shoulder_lift_joint
  - shoulder_pan_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

arm_initial_positions:
  - 1.2
  - -0.75
  - 0
  - 1.127
  - 1.58
  - 1.51

arm_scanning_positions:
  - 0
  - -0.698132
  - -0.502655
  - 2.18166
  - 1.58
  - 1.51

gripper_joint_names:
  - finger_joint

gripper_open_positions:
  - 0

gripper_close_positions:
  - 0.30