# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
  shoulder_lift_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
  shoulder_pan_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
  wrist_1_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
  wrist_2_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
  wrist_3_joint:
    has_velocity_limits: true
    min_velocity: !degrees  230.0
    max_velocity: !degrees  260.0
    has_acceleration_limits: true
    min_acceleration: 3
    max_acceleration: 4
